name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.next/cache
            **/node_modules
          key: ${{ github.workflow }}-${{ github.job }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: yarn build
        run: |
          yarn build
